-- Verdikt: consolidated schema for PostgreSQL (Supabase).
-- Ported from backend/migrations 001–013 (SQLite). Run via Supabase SQL Editor or `supabase db push`.
-- Notes:
-- - String IDs (ws_*, rel_*, etc.) stay as TEXT.
-- - SQLite INTEGER 0/1 flags → BOOLEAN.
-- - ISO datetimes → TIMESTAMPTZ (use timestamptz for new rows; migrate data with ::timestamptz).
-- - Seed data (demo users) is NOT here — use backend seed scripts or Supabase seed after cutover.

-- ─── Core ───────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS users (
  id text PRIMARY KEY,
  email text UNIQUE NOT NULL,
  password_hash text NOT NULL,
  name text,
  workspace_id text NOT NULL,
  role text NOT NULL DEFAULT 'ai_product_lead',
  created_at timestamptz NOT NULL
);

CREATE TABLE IF NOT EXISTS thresholds (
  workspace_id text NOT NULL,
  signal_id text NOT NULL,
  min_value double precision,
  max_value double precision,
  PRIMARY KEY (workspace_id, signal_id)
);

CREATE TABLE IF NOT EXISTS workspace_policies (
  workspace_id text PRIMARY KEY,
  require_ai_eval boolean NOT NULL DEFAULT true,
  ai_missing_policy text NOT NULL DEFAULT 'block_uncertified',
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL,
  cert_expiry_days integer,
  collection_timeout_policy text NOT NULL DEFAULT 'block_uncertified'
);

CREATE TABLE IF NOT EXISTS releases (
  id text PRIMARY KEY,
  workspace_id text NOT NULL,
  version text NOT NULL,
  release_type text NOT NULL,
  environment text,
  status text NOT NULL,
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL,
  release_ref text,
  trigger_source text,
  mappings_json text,
  collection_deadline timestamptz,
  verdict_issued_at timestamptz,
  ai_context_json text,
  commit_sha text,
  pr_number integer
);

CREATE TABLE IF NOT EXISTS webhook_events (
  idempotency_key text PRIMARY KEY,
  release_id text NOT NULL,
  created_at timestamptz NOT NULL
);

CREATE TABLE IF NOT EXISTS signals (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  release_id text NOT NULL,
  signal_id text NOT NULL,
  value double precision NOT NULL,
  source text,
  created_at timestamptz NOT NULL,
  idempotency_key text
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_signals_idempotency
  ON signals (release_id, signal_id, idempotency_key)
  WHERE idempotency_key IS NOT NULL;

CREATE TABLE IF NOT EXISTS overrides (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  release_id text NOT NULL UNIQUE,
  approver_type text NOT NULL,
  approver_name text NOT NULL,
  approver_role text,
  justification text NOT NULL,
  metadata_json text,
  created_at timestamptz NOT NULL,
  updated_at timestamptz
);

CREATE TABLE IF NOT EXISTS audit_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  workspace_id text NOT NULL,
  release_id text,
  event_type text NOT NULL,
  actor_type text NOT NULL,
  actor_name text NOT NULL,
  details_json text,
  created_at timestamptz NOT NULL,
  row_hash text
);

CREATE TABLE IF NOT EXISTS release_intelligence (
  release_id text PRIMARY KEY,
  workspace_id text NOT NULL,
  verdict_json text,
  override_json text,
  trace_json text,
  decision_json text,
  outcome_json text,
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL,
  baseline_health_json text,
  early_warning_json text
);

CREATE INDEX IF NOT EXISTS idx_signals_release_id ON signals (release_id);
CREATE INDEX IF NOT EXISTS idx_releases_workspace_created ON releases (workspace_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_workspace_id ON audit_events (workspace_id, id DESC);
CREATE INDEX IF NOT EXISTS idx_audit_release_id ON audit_events (release_id);

CREATE TABLE IF NOT EXISTS override_history (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  release_id text NOT NULL,
  approver_type text NOT NULL,
  approver_name text NOT NULL,
  approver_role text,
  justification text NOT NULL,
  metadata_json text,
  created_at timestamptz NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_override_history_release ON override_history (release_id, id DESC);

CREATE TABLE IF NOT EXISTS release_deltas (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  release_id text NOT NULL,
  workspace_id text NOT NULL,
  signal_id text NOT NULL,
  baseline_release_id text,
  baseline_value double precision,
  current_value double precision,
  max_allowed_drop double precision NOT NULL,
  drop_amount double precision,
  passed boolean NOT NULL,
  computed_at timestamptz NOT NULL,
  UNIQUE (release_id, signal_id)
);
CREATE INDEX IF NOT EXISTS idx_release_deltas_release ON release_deltas (release_id);

-- ─── 003 password reset ─────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS password_reset_tokens (
  id text PRIMARY KEY,
  user_id text NOT NULL,
  token_hash text NOT NULL,
  expires_at timestamptz NOT NULL,
  used_at timestamptz,
  created_at timestamptz NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_password_reset_token_hash ON password_reset_tokens (token_hash);
CREATE INDEX IF NOT EXISTS idx_password_reset_user ON password_reset_tokens (user_id);

-- ─── 004 governance hardening ─────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS cert_signatures (
  release_id text PRIMARY KEY,
  workspace_id text NOT NULL,
  algorithm text NOT NULL DEFAULT 'sha256',
  payload_hash text NOT NULL,
  signature text NOT NULL,
  signed_at timestamptz NOT NULL,
  signed_by text NOT NULL DEFAULT 'system',
  public_key_hint text
);
CREATE INDEX IF NOT EXISTS idx_cert_signatures_workspace ON cert_signatures (workspace_id, signed_at DESC);

CREATE TABLE IF NOT EXISTS baseline_policies (
  workspace_id text PRIMARY KEY,
  strategy text NOT NULL DEFAULT 'median_n',
  window_n integer NOT NULL DEFAULT 5,
  pinned_release_id text,
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL
);

CREATE TABLE IF NOT EXISTS release_early_warnings (
  release_id text PRIMARY KEY,
  workspace_id text NOT NULL,
  computed_at timestamptz NOT NULL,
  sample_pct double precision,
  warnings_json text NOT NULL DEFAULT '[]',
  overall_risk text NOT NULL DEFAULT 'stable',
  updated_at timestamptz NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_early_warnings_workspace ON release_early_warnings (workspace_id, computed_at DESC);

CREATE TABLE IF NOT EXISTS outbound_webhooks (
  id text PRIMARY KEY,
  workspace_id text NOT NULL UNIQUE,
  url text NOT NULL,
  secret text,
  events text NOT NULL DEFAULT 'CERTIFIED,UNCERTIFIED,CERTIFIED_WITH_OVERRIDE',
  enabled boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL
);

CREATE TABLE IF NOT EXISTS outbound_webhook_deliveries (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  webhook_id text NOT NULL,
  release_id text,
  event_type text NOT NULL,
  payload_json text,
  response_status integer,
  error_message text,
  delivered_at timestamptz NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_webhook_deliveries_webhook ON outbound_webhook_deliveries (webhook_id, delivered_at DESC);

CREATE TABLE IF NOT EXISTS signal_schema (
  workspace_id text NOT NULL,
  signal_id text NOT NULL,
  aliases_json text NOT NULL DEFAULT '[]',
  required boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL,
  PRIMARY KEY (workspace_id, signal_id)
);

-- ─── 005 intelligence pipeline ────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS signal_correlations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  workspace_id text NOT NULL,
  signal_a text NOT NULL,
  signal_b text NOT NULL,
  correlation double precision NOT NULL,
  sample_count integer NOT NULL,
  computed_at timestamptz NOT NULL,
  UNIQUE (workspace_id, signal_a, signal_b)
);
CREATE INDEX IF NOT EXISTS idx_correlations_ws ON signal_correlations (workspace_id);

CREATE TABLE IF NOT EXISTS failure_mode_classifications (
  release_id text NOT NULL,
  workspace_id text NOT NULL,
  failure_mode text NOT NULL,
  confidence double precision NOT NULL,
  signals_json text NOT NULL,
  computed_at timestamptz NOT NULL,
  PRIMARY KEY (release_id, failure_mode)
);
CREATE INDEX IF NOT EXISTS idx_failure_modes_ws ON failure_mode_classifications (workspace_id, computed_at DESC);

CREATE TABLE IF NOT EXISTS env_chains (
  id text PRIMARY KEY,
  workspace_id text NOT NULL,
  name text NOT NULL,
  environments text NOT NULL,
  require_all boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_env_chains_ws ON env_chains (workspace_id);

CREATE TABLE IF NOT EXISTS env_chain_links (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  chain_id text NOT NULL,
  release_id text NOT NULL,
  environment text NOT NULL,
  status text NOT NULL DEFAULT 'pending',
  certified_at timestamptz,
  created_at timestamptz NOT NULL,
  UNIQUE (chain_id, environment)
);
CREATE INDEX IF NOT EXISTS idx_chain_links_chain ON env_chain_links (chain_id);
CREATE INDEX IF NOT EXISTS idx_chain_links_release ON env_chain_links (release_id);

CREATE TABLE IF NOT EXISTS sse_tokens (
  token text PRIMARY KEY,
  workspace_id text NOT NULL,
  release_id text,
  expires_at timestamptz NOT NULL,
  created_at timestamptz NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_sse_tokens_release ON sse_tokens (release_id);

CREATE TABLE IF NOT EXISTS vcs_integrations (
  id text PRIMARY KEY,
  workspace_id text NOT NULL UNIQUE,
  provider text NOT NULL DEFAULT 'github',
  access_token text NOT NULL,
  owner text NOT NULL,
  repo text NOT NULL,
  enabled boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL
);

CREATE TABLE IF NOT EXISTS vcs_status_deliveries (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  workspace_id text NOT NULL,
  release_id text NOT NULL,
  provider text NOT NULL,
  commit_sha text,
  pr_number integer,
  status_sent text NOT NULL,
  response_code integer,
  error_message text,
  delivered_at timestamptz NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_vcs_deliveries_release ON vcs_status_deliveries (release_id);

CREATE TABLE IF NOT EXISTS override_analytics_cache (
  workspace_id text PRIMARY KEY,
  computed_at timestamptz NOT NULL,
  total_overrides integer NOT NULL DEFAULT 0,
  override_rate_pct double precision NOT NULL DEFAULT 0,
  top_approvers text NOT NULL DEFAULT '[]',
  top_signals text NOT NULL DEFAULT '[]',
  risk_distribution text NOT NULL DEFAULT '{}',
  trend_json text NOT NULL DEFAULT '[]'
);

CREATE TABLE IF NOT EXISTS signal_reliability (
  workspace_id text NOT NULL,
  signal_id text NOT NULL,
  computed_at timestamptz NOT NULL,
  sample_count integer NOT NULL DEFAULT 0,
  on_time_rate double precision NOT NULL DEFAULT 0,
  variance_score double precision NOT NULL DEFAULT 0,
  reliability double precision NOT NULL DEFAULT 0,
  grade text NOT NULL DEFAULT 'unknown',
  PRIMARY KEY (workspace_id, signal_id)
);
CREATE INDEX IF NOT EXISTS idx_reliability_ws ON signal_reliability (workspace_id);

-- ─── 006 production feedback ──────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS production_observations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  release_id text NOT NULL,
  workspace_id text NOT NULL,
  signal_name text NOT NULL,
  value double precision NOT NULL,
  observed_at timestamptz NOT NULL,
  source text NOT NULL DEFAULT 'webhook',
  idempotency_key text,
  metadata_json text,
  created_at timestamptz NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_prod_obs_release ON production_observations (release_id, signal_name);
CREATE INDEX IF NOT EXISTS idx_prod_obs_workspace ON production_observations (workspace_id, observed_at DESC);
CREATE UNIQUE INDEX IF NOT EXISTS idx_prod_obs_idempotency
  ON production_observations (release_id, signal_name, idempotency_key)
  WHERE idempotency_key IS NOT NULL;

CREATE TABLE IF NOT EXISTS outcome_alignments (
  release_id text PRIMARY KEY,
  workspace_id text NOT NULL,
  recommended_verdict text,
  actual_outcome text,
  alignment text,
  signal_deltas_json text,
  computed_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL,
  outcome_criteria_json text,
  incident_ref text,
  over_block_suggestions_json text
);
CREATE INDEX IF NOT EXISTS idx_outcome_workspace ON outcome_alignments (workspace_id, computed_at DESC);

CREATE TABLE IF NOT EXISTS production_adjustment_cache (
  workspace_id text PRIMARY KEY,
  computed_at timestamptz NOT NULL,
  miss_rate_pct double precision NOT NULL DEFAULT 0,
  over_block_rate_pct double precision NOT NULL DEFAULT 0,
  signal_drift_json text NOT NULL DEFAULT '{}',
  confidence_modifier double precision NOT NULL DEFAULT 0,
  sample_count integer NOT NULL DEFAULT 0
);

-- ─── 008 VCS monitoring ───────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS vcs_monitoring_windows (
  release_id text PRIMARY KEY,
  workspace_id text NOT NULL,
  commit_sha text,
  pr_number integer,
  monitoring_start timestamptz NOT NULL,
  monitoring_end timestamptz NOT NULL,
  window_minutes integer NOT NULL DEFAULT 120,
  status text NOT NULL DEFAULT 'pending',
  last_scanned_at timestamptz,
  scan_count integer NOT NULL DEFAULT 0,
  findings_json text,
  inferred_signals_json text,
  inferred_outcome text,
  error_message text,
  created_at timestamptz NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_vcs_windows_status ON vcs_monitoring_windows (status, monitoring_end);
CREATE INDEX IF NOT EXISTS idx_vcs_windows_workspace ON vcs_monitoring_windows (workspace_id, created_at DESC);

-- ─── 010 signal integrations + CSV ────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS signal_integrations (
  workspace_id text NOT NULL,
  source_id text NOT NULL,
  api_key text NOT NULL,
  extra_json text,
  verified_at timestamptz,
  last_verify_error text,
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL,
  PRIMARY KEY (workspace_id, source_id)
);

CREATE TABLE IF NOT EXISTS signal_csv_imports (
  id text PRIMARY KEY,
  workspace_id text NOT NULL,
  filename text NOT NULL,
  row_count integer NOT NULL,
  columns_json text NOT NULL,
  preview_json text NOT NULL,
  created_at timestamptz NOT NULL,
  rows_json text
);
CREATE INDEX IF NOT EXISTS idx_signal_csv_imports_workspace ON signal_csv_imports (workspace_id);

-- ─── 012–013 waitlist ─────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS waitlist_requests (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  email text NOT NULL,
  company text NOT NULL,
  role text,
  message text,
  created_at timestamptz NOT NULL,
  source_ip text,
  q_role text,
  q_team_size text,
  q_release_process text,
  q_pain_points text,
  q_goal text
);
CREATE INDEX IF NOT EXISTS idx_waitlist_requests_created ON waitlist_requests (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_waitlist_requests_email ON waitlist_requests (email);
